"""ETS connector SDK v1."""

from ets.connectors.conformance import ConnectorConformanceHarness, ConnectorConformanceReport
from ets.connectors.models import (
    CAPTURE_ENVELOPE_VERSION,
    CONNECTOR_DEFINITION_SCHEMA_VERSION,
    CONNECTOR_INSTANCE_SCHEMA_VERSION,
    CONNECTOR_SDK_CONTRACT_VERSION,
    GATEWAY_CONNECTOR_HOST_VERSION,
    ConnectorAuthentication,
    ConnectorCapabilities,
    ConnectorCheckpointPolicy,
    ConnectorCheckpointV1,
    ConnectorCollection,
    ConnectorCollectionResultV1,
    ConnectorConfigurationSchema,
    ConnectorDefinitionV1,
    ConnectorEvidenceCandidateV1,
    ConnectorGapPolicy,
    ConnectorHealthV1,
    ConnectorInstanceV1,
    ConnectorPolicyBinding,
    ConnectorReconciliationResultV1,
    ConnectorRetryPolicy,
    ConnectorScope,
    ConnectorSource,
)
from ets.connectors.native import (
    NATIVE_CONNECTOR_BINDINGS,
    NativeConnectorAdapter,
    NativeConnectorBinding,
    load_native_connector_registry,
)
from ets.connectors.registry import (
    ConnectorCompatibilityError,
    ConnectorNotFoundError,
    ConnectorRegistry,
    ConnectorRegistryError,
)
from ets.connectors.sdk import (
    ConnectorAdapter,
    ConnectorCapabilityError,
    ConnectorConfigurationError,
)

__all__ = [
    "CAPTURE_ENVELOPE_VERSION",
    "CONNECTOR_DEFINITION_SCHEMA_VERSION",
    "CONNECTOR_INSTANCE_SCHEMA_VERSION",
    "CONNECTOR_SDK_CONTRACT_VERSION",
    "GATEWAY_CONNECTOR_HOST_VERSION",
    "NATIVE_CONNECTOR_BINDINGS",
    "ConnectorAdapter",
    "ConnectorAuthentication",
    "ConnectorCapabilities",
    "ConnectorCapabilityError",
    "ConnectorCheckpointPolicy",
    "ConnectorCheckpointV1",
    "ConnectorCollection",
    "ConnectorCollectionResultV1",
    "ConnectorCompatibilityError",
    "ConnectorConfigurationError",
    "ConnectorConfigurationSchema",
    "ConnectorConformanceHarness",
    "ConnectorConformanceReport",
    "ConnectorDefinitionV1",
    "ConnectorEvidenceCandidateV1",
    "ConnectorGapPolicy",
    "ConnectorHealthV1",
    "ConnectorInstanceV1",
    "ConnectorNotFoundError",
    "ConnectorPolicyBinding",
    "ConnectorReconciliationResultV1",
    "ConnectorRegistry",
    "ConnectorRegistryError",
    "ConnectorRetryPolicy",
    "ConnectorScope",
    "ConnectorSource",
    "NativeConnectorAdapter",
    "NativeConnectorBinding",
    "load_native_connector_registry",
]
