"""ETS Fleet enrollment and device lifecycle primitives."""

from ets.fleet.enrollment import (
    AttestationClass,
    AuthMethod,
    AuthorizationDecision,
    AuthorizationReason,
    DeviceEnrollmentRecord,
    DeviceEnrollmentService,
    DeviceProfile,
    EnrollmentErrorCode,
    EnrollmentIdentityValidator,
    EnrollmentStore,
    EnrollmentValidationError,
    InMemoryEnrollmentStore,
    KeyCustody,
    ProductType,
    ProvisioningBackend,
    RegistrationState,
    RotationWindow,
    ScopeBinding,
    derive_device_id,
)

__all__ = [
    "AttestationClass",
    "AuthMethod",
    "AuthorizationDecision",
    "AuthorizationReason",
    "DeviceEnrollmentRecord",
    "DeviceEnrollmentService",
    "DeviceProfile",
    "EnrollmentErrorCode",
    "EnrollmentIdentityValidator",
    "EnrollmentStore",
    "EnrollmentValidationError",
    "InMemoryEnrollmentStore",
    "KeyCustody",
    "ProductType",
    "ProvisioningBackend",
    "RegistrationState",
    "RotationWindow",
    "ScopeBinding",
    "derive_device_id",
]
