@description('Existing Fleet C3B Container App name.')
@minLength(1)
param containerAppName string

@description('Existing Fleet C3B internal Container Apps managed environment name.')
@minLength(1)
param managedEnvironmentName string

@description('Microsoft Entra tenant ID for the single-tenant Fleet control plane.')
@minLength(1)
param entraTenantId string

@description('Microsoft Entra application/client ID used by Container Apps EasyAuth.')
@minLength(1)
param entraClientId string

@description('Exact Fleet audience also enforced by the BFF trusted-context adapter.')
@minLength(1)
param entraAudience string

@description('One or more Microsoft Entra group object IDs authorized to reach Fleet.')
@minLength(1)
param operatorGroupObjectIds array

@description('Existing Container App secret setting containing the EasyAuth client secret. The secret value is never accepted by this template.')
@minLength(1)
param entraClientSecretSettingName string = 'MICROSOFT_PROVIDER_AUTHENTICATION_SECRET'

@description('Globally unique Azure Front Door endpoint label used only for pre-hostname qualification.')
@minLength(3)
param frontDoorEndpointName string = 'ets-fleet-${uniqueString(subscription().id, resourceGroup().id)}'

@description('Front Door WAF requests permitted per client IP in a one-minute window.')
@minValue(30)
@maxValue(600)
param rateLimitThreshold int = 120

var resourceToken = uniqueString(resourceGroup().id, containerAppName)
var frontDoorProfileName = take('ets-${resourceToken}-fleet-afd', 128)
var originGroupName = 'fleet-private-origin'
var originName = 'fleet-container-app'
var routeName = 'fleet-qualified-default-route'
var wafPolicyName = take('ets-${resourceToken}-fleet-waf', 128)
var securityPolicyName = 'fleet-default-domain-waf'
var entraIssuer = 'https://login.microsoftonline.com/${entraTenantId}/v2.0'
var documentationAddressRange = '192.0.2.0/24'

resource managedEnvironment 'Microsoft.App/managedEnvironments@2026-01-01' existing = {
  name: managedEnvironmentName
}

resource containerApp 'Microsoft.App/containerApps@2025-01-01' existing = {
  name: containerAppName
}

resource authConfig 'Microsoft.App/containerApps/authConfigs@2026-01-01' = {
  parent: containerApp
  name: 'current'
  properties: {
    platform: {
      enabled: true
    }
    globalValidation: {
      excludedPaths: [
        '/fleet/readyz'
      ]
      redirectToProvider: 'azureactivedirectory'
      unauthenticatedClientAction: 'RedirectToLoginPage'
    }
    httpSettings: {
      requireHttps: true
      forwardProxy: {
        convention: 'Standard'
      }
    }
    identityProviders: {
      azureActiveDirectory: {
        enabled: true
        registration: {
          clientId: entraClientId
          clientSecretSettingName: entraClientSecretSettingName
          openIdIssuer: entraIssuer
        }
        validation: {
          allowedAudiences: [
            entraClientId
            entraAudience
          ]
          defaultAuthorizationPolicy: {
            allowedApplications: []
            allowedPrincipals: {
              groups: operatorGroupObjectIds
              identities: []
            }
          }
          jwtClaimChecks: {
            allowedClientApplications: []
            allowedGroups: operatorGroupObjectIds
          }
        }
      }
    }
    login: {
      cookieExpiration: {
        convention: 'FixedTime'
        timeToExpiration: '08:00:00'
      }
      nonce: {
        validateNonce: true
        nonceExpirationInterval: '00:05:00'
      }
      preserveUrlFragmentsForLogins: false
      tokenStore: {
        enabled: false
      }
    }
  }
}

resource frontDoorProfile 'Microsoft.Cdn/profiles@2025-12-01' = {
  name: frontDoorProfileName
  location: 'global'
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    originResponseTimeoutSeconds: 30
  }
}

resource frontDoorEndpoint 'Microsoft.Cdn/profiles/afdEndpoints@2025-12-01' = {
  parent: frontDoorProfile
  name: frontDoorEndpointName
  location: 'global'
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'ResourceGroupReuse'
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2025-12-01' = {
  parent: frontDoorProfile
  name: originGroupName
  properties: {
    healthProbeSettings: {
      probeIntervalInSeconds: 60
      probePath: '/fleet/readyz'
      probeProtocol: 'Https'
      probeRequestType: 'GET'
    }
    loadBalancingSettings: {
      additionalLatencyInMilliseconds: 0
      sampleSize: 4
      successfulSamplesRequired: 3
    }
    sessionAffinityState: 'Disabled'
  }
}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2025-12-01' = {
  parent: originGroup
  name: originName
  properties: {
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
    hostName: containerApp.properties.configuration.ingress.fqdn
    httpPort: 80
    httpsPort: 443
    originHostHeader: containerApp.properties.configuration.ingress.fqdn
    priority: 1
    weight: 1000
    sharedPrivateLinkResource: {
      privateLink: {
        id: managedEnvironment.id
      }
      privateLinkLocation: managedEnvironment.location
      groupId: 'managedEnvironments'
      requestMessage: 'ETS Fleet C3C protected Front Door qualification origin.'
      status: 'Pending'
    }
  }
}

resource route 'Microsoft.Cdn/profiles/afdEndpoints/routes@2025-12-01' = {
  parent: frontDoorEndpoint
  name: routeName
  dependsOn: [
    origin
    authConfig
  ]
  properties: {
    enabledState: 'Enabled'
    forwardingProtocol: 'HttpsOnly'
    httpsRedirect: 'Enabled'
    linkToDefaultDomain: 'Enabled'
    originGroup: {
      id: originGroup.id
    }
    patternsToMatch: [
      '/*'
    ]
    supportedProtocols: [
      'Https'
    ]
  }
}

resource wafPolicy 'Microsoft.Cdn/cdnWebApplicationFirewallPolicies@2025-12-01' = {
  name: wafPolicyName
  location: 'global'
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: 'Prevention'
    }
    managedRules: {
      managedRuleSets: [
        {
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.2'
        }
        {
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.1'
        }
      ]
    }
    rateLimitRules: {
      rules: [
        {
          name: 'PerClientFleetRateLimit'
          priority: 100
          enabledState: 'Enabled'
          rateLimitThreshold: rateLimitThreshold
          rateLimitDurationInMinutes: 1
          action: 'Block'
          matchConditions: [
            {
              matchVariable: 'RemoteAddr'
              operator: 'IPMatch'
              negateCondition: true
              matchValue: [
                documentationAddressRange
              ]
            }
          ]
        }
      ]
    }
  }
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2025-12-01' = {
  parent: frontDoorProfile
  name: securityPolicyName
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: {
        id: wafPolicy.id
      }
      associations: [
        {
          domains: [
            {
              id: frontDoorEndpoint.id
            }
          ]
          patternsToMatch: [
            '/*'
          ]
        }
      ]
    }
  }
}

output frontDoorProfileName string = frontDoorProfile.name
output frontDoorEndpointName string = frontDoorEndpoint.name
output frontDoorEndpointHostName string = frontDoorEndpoint.properties.hostName
output frontDoorRouteName string = route.name
output privateLinkTargetId string = managedEnvironment.id
output privateLinkApprovalRequired bool = true
output wafMode string = 'Prevention'
output authenticationProvider string = 'MicrosoftEntraID'
output tokenStoreEnabled bool = false
output defaultDomainQualificationEnabled bool = true
output publicHostnameActivated bool = false
