@description('Existing hosted Edge Virtual container app name.')
@minLength(1)
param containerAppName string

@description('Existing internal Container Apps managed environment name.')
@minLength(1)
param managedEnvironmentName string

@description('Microsoft Entra tenant ID for the single-tenant hosted demo app registration.')
@minLength(36)
param entraTenantId string

@description('Microsoft Entra application/client ID used by Container Apps built-in authentication.')
@minLength(36)
param entraClientId string

@description('One or more Microsoft Entra group object IDs authorized to use the hosted demo.')
@minLength(1)
param operatorGroupObjectIds array

@description('Existing Container Apps app-setting name containing the EasyAuth confidential client secret. The secret VALUE is never accepted by this template.')
@minLength(1)
param entraClientSecretSettingName string = 'MICROSOFT_PROVIDER_AUTHENTICATION_SECRET'

@description('Public hostname for the authenticated Edge Virtual demonstration.')
@minLength(3)
param customDomainHostName string = 'edge-demo.lanternprotocol.net'

@description('Globally unique Azure Front Door endpoint label.')
@minLength(3)
param frontDoorEndpointName string = 'ets-edge-demo-${uniqueString(subscription().id, resourceGroup().id)}'

@description('Front Door WAF requests permitted per client IP in the configured one-minute window.')
@minValue(30)
@maxValue(600)
param rateLimitThreshold int = 120

var resourceToken = uniqueString(resourceGroup().id, containerAppName, customDomainHostName)
var frontDoorProfileName = take('ets-${resourceToken}-edge-afd', 128)
var originGroupName = 'edge-private-origin'
var originName = 'edge-container-app'
var routeName = 'edge-demo-https'
var customDomainName = take('edge-demo-${resourceToken}', 128)
var wafPolicyName = take('ets-${resourceToken}-edge-waf', 128)
var securityPolicyName = 'edge-demo-waf'
var entraIssuer = 'https://login.microsoftonline.com/${entraTenantId}/v2.0'
var documentationAddressRange = '192.0.2.0/24'

resource managedEnvironment 'Microsoft.App/managedEnvironments@2026-01-01' existing = {
  name: managedEnvironmentName
}

resource containerApp 'Microsoft.App/containerApps@2025-01-01' existing = {
  name: containerAppName
}

resource authConfig 'Microsoft.App/containerApps/authConfigs@2026-01-01' = {
  parent: containerApp
  name: 'current'
  properties: {
    platform: {
      enabled: true
    }
    globalValidation: {
      excludedPaths: [
        '/afd-healthz'
      ]
      redirectToProvider: 'azureactivedirectory'
      unauthenticatedClientAction: 'RedirectToLoginPage'
    }
    httpSettings: {
      requireHttps: true
      forwardProxy: {
        convention: 'Standard'
      }
    }
    identityProviders: {
      azureActiveDirectory: {
        enabled: true
        registration: {
          clientId: entraClientId
          clientSecretSettingName: entraClientSecretSettingName
          openIdIssuer: entraIssuer
        }
        validation: {
          allowedAudiences: [
            entraClientId
            'api://${entraClientId}'
          ]
          defaultAuthorizationPolicy: {
            allowedApplications: []
            allowedPrincipals: {
              groups: operatorGroupObjectIds
              identities: []
            }
          }
          jwtClaimChecks: {
            allowedClientApplications: []
            allowedGroups: operatorGroupObjectIds
          }
        }
      }
    }
    login: {
      cookieExpiration: {
        convention: 'FixedTime'
        timeToExpiration: '08:00:00'
      }
      nonce: {
        validateNonce: true
        nonceExpirationInterval: '00:05:00'
      }
      preserveUrlFragmentsForLogins: false
      tokenStore: {
        enabled: false
      }
    }
  }
}

resource frontDoorProfile 'Microsoft.Cdn/profiles@2025-12-01' = {
  name: frontDoorProfileName
  location: 'global'
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    originResponseTimeoutSeconds: 30
  }
}

resource frontDoorEndpoint 'Microsoft.Cdn/profiles/afdEndpoints@2025-12-01' = {
  parent: frontDoorProfile
  name: frontDoorEndpointName
  location: 'global'
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'ResourceGroupReuse'
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2025-12-01' = {
  parent: frontDoorProfile
  name: originGroupName
  properties: {
    healthProbeSettings: {
      probeIntervalInSeconds: 60
      probePath: '/afd-healthz'
      probeProtocol: 'Https'
      probeRequestType: 'GET'
    }
    loadBalancingSettings: {
      additionalLatencyInMilliseconds: 0
      sampleSize: 4
      successfulSamplesRequired: 3
    }
    sessionAffinityState: 'Disabled'
  }
}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2025-12-01' = {
  parent: originGroup
  name: originName
  properties: {
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
    hostName: containerApp.properties.configuration.ingress.fqdn
    httpPort: 80
    httpsPort: 443
    originHostHeader: containerApp.properties.configuration.ingress.fqdn
    priority: 1
    weight: 1000
    sharedPrivateLinkResource: {
      privateLink: {
        id: managedEnvironment.id
      }
      privateLinkLocation: managedEnvironment.location
      groupId: 'managedEnvironments'
      requestMessage: 'Approve only for the ETS authenticated Edge Virtual demo Front Door origin.'
      status: 'Pending'
    }
  }
}

resource customDomain 'Microsoft.Cdn/profiles/customDomains@2025-12-01' = {
  parent: frontDoorProfile
  name: customDomainName
  properties: {
    hostName: customDomainHostName
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      cipherSuiteSetType: 'TLS12_2023'
    }
  }
}

resource route 'Microsoft.Cdn/profiles/afdEndpoints/routes@2025-12-01' = {
  parent: frontDoorEndpoint
  name: routeName
  dependsOn: [
    origin
    authConfig
  ]
  properties: {
    enabledState: 'Enabled'
    forwardingProtocol: 'HttpsOnly'
    httpsRedirect: 'Disabled'
    linkToDefaultDomain: 'Disabled'
    originGroup: {
      id: originGroup.id
    }
    patternsToMatch: [
      '/*'
    ]
    supportedProtocols: [
      'Https'
    ]
    customDomains: [
      {
        id: customDomain.id
      }
    ]
  }
}

resource wafPolicy 'Microsoft.Cdn/cdnWebApplicationFirewallPolicies@2025-12-01' = {
  name: wafPolicyName
  location: 'global'
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: 'Prevention'
    }
    managedRules: {
      managedRuleSets: [
        {
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.2'
        }
        {
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.1'
        }
      ]
    }
    rateLimitRules: {
      rules: [
        {
          name: 'PerClientDemoRateLimit'
          priority: 100
          enabledState: 'Enabled'
          rateLimitThreshold: rateLimitThreshold
          rateLimitDurationInMinutes: 1
          action: 'Block'
          matchConditions: [
            {
              matchVariable: 'RemoteAddr'
              operator: 'IPMatch'
              negateCondition: true
              matchValue: [
                documentationAddressRange
              ]
            }
          ]
        }
      ]
    }
  }
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2025-12-01' = {
  parent: frontDoorProfile
  name: securityPolicyName
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: {
        id: wafPolicy.id
      }
      associations: [
        {
          domains: [
            {
              id: customDomain.id
            }
          ]
          patternsToMatch: [
            '/*'
          ]
        }
      ]
    }
  }
}

output frontDoorProfileName string = frontDoorProfile.name
output frontDoorEndpointName string = frontDoorEndpoint.name
output frontDoorEndpointHostName string = frontDoorEndpoint.properties.hostName
output publicDemoHostName string = customDomainHostName
output privateLinkTargetId string = managedEnvironment.id
output privateLinkApprovalRequired bool = true
output wafMode string = 'Prevention'
output authenticationProvider string = 'MicrosoftEntraID'
