"""Validate ETS Core import boundaries and public API stability."""

from __future__ import annotations

import argparse
import ast
import importlib
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "docs/core/core_boundary_manifest.json"


class BoundaryViolation(RuntimeError):
    """Raised when a normative Core boundary rule is violated."""


def _load_manifest(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    required = {"normative_modules", "public_api", "forbidden_import_prefixes"}
    missing = required.difference(data)
    if missing:
        raise BoundaryViolation(f"boundary manifest missing keys: {sorted(missing)}")
    return data


def _module_path(module: str) -> Path:
    path = REPO_ROOT.joinpath(*module.split(".")).with_suffix(".py")
    if not path.is_file():
        raise BoundaryViolation(f"normative module does not exist: {module}")
    return path


def _imports_for(module: str) -> set[str]:
    tree = ast.parse(_module_path(module).read_text(encoding="utf-8"), filename=module)
    imports: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.add(node.module)
    return imports


def _is_forbidden(import_name: str, prefixes: tuple[str, ...]) -> bool:
    return any(import_name == prefix or import_name.startswith(f"{prefix}.") for prefix in prefixes)


def _core_dependency(import_name: str, normative: set[str]) -> str | None:
    matches = [module for module in normative if import_name == module]
    return matches[0] if matches else None


def _find_cycle(graph: dict[str, set[str]]) -> list[str] | None:
    visiting: set[str] = set()
    visited: set[str] = set()
    stack: list[str] = []

    def visit(node: str) -> list[str] | None:
        if node in visiting:
            index = stack.index(node)
            return [*stack[index:], node]
        if node in visited:
            return None
        visiting.add(node)
        stack.append(node)
        for dependency in sorted(graph[node]):
            cycle = visit(dependency)
            if cycle:
                return cycle
        stack.pop()
        visiting.remove(node)
        visited.add(node)
        return None

    for node in sorted(graph):
        cycle = visit(node)
        if cycle:
            return cycle
    return None


def validate(manifest_path: Path = DEFAULT_MANIFEST) -> dict[str, set[str]]:
    """Validate imports, cycles, and the frozen public API manifest."""

    manifest = _load_manifest(manifest_path)
    normative = set(manifest["normative_modules"])
    forbidden = tuple(manifest["forbidden_import_prefixes"])
    graph: dict[str, set[str]] = defaultdict(set)
    violations: list[str] = []

    for module in sorted(normative):
        graph[module]
        for imported in sorted(_imports_for(module)):
            if _is_forbidden(imported, forbidden):
                violations.append(f"{module} imports forbidden dependency {imported}")
            dependency = _core_dependency(imported, normative)
            if dependency and dependency != module:
                graph[module].add(dependency)

    cycle = _find_cycle(graph)
    if cycle:
        violations.append(f"normative dependency cycle: {' -> '.join(cycle)}")

    api = importlib.import_module("ets.core.api")
    actual = list(api.__all__)
    expected = list(manifest["public_api"])
    if actual != expected:
        violations.append(
            "ets.core.api.__all__ differs from core_boundary_manifest.json: "
            f"expected={expected!r}, actual={actual!r}"
        )

    if violations:
        raise BoundaryViolation("\n".join(violations))
    return graph


def render_graph(graph: dict[str, set[str]]) -> str:
    """Render a deterministic Markdown dependency graph."""

    lines = [
        "# ETS Core Normative Dependency Graph",
        "",
        "Generated by `tools/check_core_boundaries.py`.",
        "",
        "```text",
    ]
    for module in sorted(graph):
        dependencies = ", ".join(sorted(graph[module])) or "(none)"
        lines.append(f"{module} -> {dependencies}")
    lines.extend(["```", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--write-graph", type=Path)
    args = parser.parse_args()

    try:
        graph = validate(args.manifest)
    except BoundaryViolation as exc:
        print(f"FAILED\n{exc}")
        return 1

    if args.write_graph:
        args.write_graph.write_text(render_graph(graph), encoding="utf-8")
    print("PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
